-- =====================================================
-- K-MaaS Platform - Complete Database Schema
-- Oracle 11g Express Edition
-- =====================================================
-- 생성일: 2026-01-12
-- 설명: 서울·경기·인천 통합 모빌리티 플랫폼 전체 테이블 스키마
-- =====================================================

-- 기존 테이블 삭제 (역순)
DROP TABLE PUBLIC_PARKING CASCADE CONSTRAINTS;
DROP TABLE BIKE_STATIONS CASCADE CONSTRAINTS;
DROP TABLE SUBWAY_STATION CASCADE CONSTRAINTS;
DROP TABLE SHOP CASCADE CONSTRAINTS;
DROP TABLE POLICY CASCADE CONSTRAINTS;
DROP TABLE USAGE_RECORDS CASCADE CONSTRAINTS;
DROP TABLE POINT_TRANSACTIONS CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

-- 시퀀스 삭제
DROP SEQUENCE USER_SEQ;
DROP SEQUENCE POINT_SEQ;
DROP SEQUENCE USAGE_SEQ;
DROP SEQUENCE SUBWAY_STATION_SEQ;
DROP SEQUENCE POLICY_SEQ;
DROP SEQUENCE SHOP_SEQ;
DROP SEQUENCE PARKING_SEQ;

-- =====================================================
-- 1. 회원 테이블 (USERS)
-- =====================================================
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    PHONE VARCHAR2(20),
    POINTS NUMBER DEFAULT 1000,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE USERS IS '회원 정보 테이블';
COMMENT ON COLUMN USERS.USER_ID IS '회원 ID (PK)';
COMMENT ON COLUMN USERS.NAME IS '회원 이름';
COMMENT ON COLUMN USERS.EMAIL IS '이메일 (고유값)';
COMMENT ON COLUMN USERS.PASSWORD IS '비밀번호 (암호화 저장)';
COMMENT ON COLUMN USERS.PHONE IS '전화번호';
COMMENT ON COLUMN USERS.POINTS IS '보유 포인트 (가입 시 1000P 지급)';

-- =====================================================
-- 2. 포인트 거래 내역 테이블 (POINT_TRANSACTIONS)
-- =====================================================
CREATE SEQUENCE POINT_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE POINT_TRANSACTIONS (
    TRANSACTION_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    AMOUNT NUMBER NOT NULL,
    TYPE VARCHAR2(20) NOT NULL CHECK (TYPE IN ('EARN', 'USE')),
    REASON VARCHAR2(200),
    TRANSACTION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_POINT_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

COMMENT ON TABLE POINT_TRANSACTIONS IS '포인트 거래 내역 테이블';
COMMENT ON COLUMN POINT_TRANSACTIONS.TYPE IS 'EARN: 적립, USE: 사용';

-- =====================================================
-- 3. 이용 기록 테이블 (USAGE_RECORDS)
-- =====================================================
CREATE SEQUENCE USAGE_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE USAGE_RECORDS (
    RECORD_ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(100),
    TRANSPORT_TYPE VARCHAR2(20) CHECK (TRANSPORT_TYPE IN ('BUS', 'SUBWAY', 'TRAIN', 'BIKE', 'PARKING')),
    ROUTE_INFO VARCHAR2(500),
    USAGE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REGION VARCHAR2(50),
    POINTS NUMBER,
    POLICY_APPLIED CHAR(1) DEFAULT '0' CHECK (POLICY_APPLIED IN ('0', '1')),
    DAY_OF_WEEK VARCHAR2(10)
);

COMMENT ON TABLE USAGE_RECORDS IS '교통수단 이용 기록 테이블';
COMMENT ON COLUMN USAGE_RECORDS.TRANSPORT_TYPE IS '교통수단 타입: BUS, SUBWAY, TRAIN, BIKE, PARKING';
COMMENT ON COLUMN USAGE_RECORDS.POLICY_APPLIED IS '정책 적용 여부: 0=미적용, 1=적용';

-- =====================================================
-- 4. 지하철역 테이블 (SUBWAY_STATION)
-- =====================================================
CREATE SEQUENCE SUBWAY_STATION_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE SUBWAY_STATION (
    ID NUMBER PRIMARY KEY,
    STATION_NAME VARCHAR2(100) NOT NULL,
    LINE_NUMBER VARCHAR2(10) NOT NULL,
    LATITUDE NUMBER NOT NULL,
    LONGITUDE NUMBER NOT NULL,
    STATION_NUMBER VARCHAR2(10),
    STATION_CODE VARCHAR2(20) UNIQUE,
    ADDRESS VARCHAR2(200),
    IS_TRANSFER CHAR(1) DEFAULT '0' CHECK (IS_TRANSFER IN ('0', '1')),
    TRANSFER_LINES VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE SUBWAY_STATION IS '지하철역 정보 테이블 (서울 1~9호선)';
COMMENT ON COLUMN SUBWAY_STATION.LINE_NUMBER IS '노선 번호: 1, 2, 3, ..., 9';
COMMENT ON COLUMN SUBWAY_STATION.IS_TRANSFER IS '환승역 여부: 0=일반역, 1=환승역';
COMMENT ON COLUMN SUBWAY_STATION.TRANSFER_LINES IS '환승 가능 노선 (쉼표 구분, 예: 2,3,9)';

-- 지하철역 인덱스
CREATE INDEX IDX_SUBWAY_LINE ON SUBWAY_STATION(LINE_NUMBER);
CREATE INDEX IDX_SUBWAY_NAME ON SUBWAY_STATION(STATION_NAME);

-- =====================================================
-- 5. 따릉이/공유자전거 대여소 테이블 (BIKE_STATIONS)
-- =====================================================
CREATE TABLE BIKE_STATIONS (
    STATION_ID VARCHAR2(50) PRIMARY KEY,
    STATION_NAME VARCHAR2(200) NOT NULL,
    LATITUDE NUMBER NOT NULL,
    LONGITUDE NUMBER NOT NULL,
    AVAILABLE_BIKES NUMBER DEFAULT 0,
    TOTAL_DOCKS NUMBER DEFAULT 0,
    DISTRICT VARCHAR2(50),
    ADDRESS VARCHAR2(300),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE BIKE_STATIONS IS '따릉이/공유자전거 대여소 정보 테이블';
COMMENT ON COLUMN BIKE_STATIONS.AVAILABLE_BIKES IS '대여 가능한 자전거 수';
COMMENT ON COLUMN BIKE_STATIONS.TOTAL_DOCKS IS '전체 거치대 수';

-- 따릉이 대여소 인덱스
CREATE INDEX IDX_BIKE_DISTRICT ON BIKE_STATIONS(DISTRICT);

-- =====================================================
-- 6. 공영 주차장 테이블 (PUBLIC_PARKING)
-- =====================================================
CREATE SEQUENCE PARKING_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE PUBLIC_PARKING (
    PARKING_ID NUMBER PRIMARY KEY,
    PARKING_CODE VARCHAR2(50) UNIQUE,
    PARKING_NAME VARCHAR2(200) NOT NULL,
    ADDRESS VARCHAR2(300),
    LATITUDE NUMBER,
    LONGITUDE NUMBER,
    TOTAL_SPACES NUMBER,
    AVAILABLE_SPACES NUMBER,
    PARKING_TYPE VARCHAR2(20),
    OPERATION_TYPE VARCHAR2(20),
    WEEKDAY_BEGIN_TIME VARCHAR2(10),
    WEEKDAY_END_TIME VARCHAR2(10),
    WEEKEND_BEGIN_TIME VARCHAR2(10),
    WEEKEND_END_TIME VARCHAR2(10),
    RATES VARCHAR2(200),
    PAY_METHOD VARCHAR2(100),
    TELEPHONE VARCHAR2(20),
    REGION VARCHAR2(20),
    DISTRICT VARCHAR2(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE PUBLIC_PARKING IS '공영 주차장 정보 테이블 (서울·경기)';
COMMENT ON COLUMN PUBLIC_PARKING.PARKING_TYPE IS '주차장 타입: 노외, 노상';
COMMENT ON COLUMN PUBLIC_PARKING.OPERATION_TYPE IS '운영 타입: 공영, 민영';
COMMENT ON COLUMN PUBLIC_PARKING.REGION IS '지역: 서울, 경기';

-- 주차장 인덱스
CREATE INDEX IDX_PARKING_REGION ON PUBLIC_PARKING(REGION);
CREATE INDEX IDX_PARKING_DISTRICT ON PUBLIC_PARKING(DISTRICT);
CREATE INDEX IDX_PARKING_CODE ON PUBLIC_PARKING(PARKING_CODE);

-- =====================================================
-- 7. 정책 테이블 (POLICY)
-- =====================================================
CREATE SEQUENCE POLICY_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE POLICY (
    POLICY_ID NUMBER PRIMARY KEY,
    POLICY_NAME VARCHAR2(100) NOT NULL,
    POLICY_TYPE VARCHAR2(20) NOT NULL CHECK (POLICY_TYPE IN ('off-peak', 'eco', 'flat', 'area')),
    ENABLED CHAR(1) DEFAULT '1' CHECK (ENABLED IN ('0', '1')),
    CONFIG CLOB,
    START_DATE DATE,
    END_DATE DATE,
    TARGET_AREA VARCHAR2(200),
    INCENTIVE_POINT NUMBER,
    DESCRIPTION CLOB,
    TARGET_GROUP VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE POLICY IS '정책 관리 테이블 (비혼잡시간대, 친환경, 정액요금제, 사용지지정)';
COMMENT ON COLUMN POLICY.POLICY_TYPE IS 'off-peak: 비혼잡, eco: 친환경, flat: 정액, area: 사용지지정';
COMMENT ON COLUMN POLICY.ENABLED IS '활성화 여부: 0=비활성, 1=활성';
COMMENT ON COLUMN POLICY.CONFIG IS '정책 설정값 (JSON 형식)';

-- =====================================================
-- 8. 제휴 상점 테이블 (SHOP)
-- =====================================================
CREATE SEQUENCE SHOP_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE SHOP (
    SHOP_ID NUMBER PRIMARY KEY,
    SHOP_NAME VARCHAR2(100) NOT NULL,
    CATEGORY VARCHAR2(50) NOT NULL,
    ADDRESS VARCHAR2(200) NOT NULL,
    LATITUDE NUMBER NOT NULL,
    LONGITUDE NUMBER NOT NULL,
    PHONE VARCHAR2(20),
    RATING NUMBER(2,1),
    DISCOUNT_RATE NUMBER NOT NULL,
    VISIT_COUNT NUMBER DEFAULT 0,
    OPENING_TIME VARCHAR2(10),
    CLOSING_TIME VARCHAR2(10),
    STATUS VARCHAR2(20) DEFAULT 'open' CHECK (STATUS IN ('open', 'closed', 'preparing')),
    PARTNER_SINCE TIMESTAMP,
    ACTIVE CHAR(1) DEFAULT '1' CHECK (ACTIVE IN ('0', '1')),
    IMAGE_URL VARCHAR2(500),
    DESCRIPTION CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE SHOP IS '제휴 상점 정보 테이블';
COMMENT ON COLUMN SHOP.CATEGORY IS '카테고리: 카페, 음식점, 편의점, 주유소, 운동';
COMMENT ON COLUMN SHOP.STATUS IS '영업 상태: open, closed, preparing';
COMMENT ON COLUMN SHOP.ACTIVE IS '제휴 활성화 여부: 0=비활성, 1=활성';

-- 상점 인덱스
CREATE INDEX IDX_SHOP_CATEGORY ON SHOP(CATEGORY);
CREATE INDEX IDX_SHOP_STATUS ON SHOP(STATUS);

-- =====================================================
-- 샘플 데이터 삽입
-- =====================================================

-- 1. 회원 샘플 데이터
INSERT INTO USERS (USER_ID, NAME, EMAIL, PASSWORD, PHONE, POINTS) VALUES
(USER_SEQ.NEXTVAL, '김철수', 'kim@example.com', '$2a$10$dummyHashedPassword1', '010-1234-5678', 5000);
INSERT INTO USERS (USER_ID, NAME, EMAIL, PASSWORD, PHONE, POINTS) VALUES
(USER_SEQ.NEXTVAL, '이영희', 'lee@example.com', '$2a$10$dummyHashedPassword2', '010-2345-6789', 3000);
INSERT INTO USERS (USER_ID, NAME, EMAIL, PASSWORD, PHONE, POINTS) VALUES
(USER_SEQ.NEXTVAL, '박민수', 'park@example.com', '$2a$10$dummyHashedPassword3', '010-3456-7890', 7000);

-- 2. 지하철역 샘플 데이터 (주요 역)
INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER) VALUES
(SUBWAY_STATION_SEQ.NEXTVAL, '강남역', '2', 37.498095, 127.027610, '222', '1');
INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER) VALUES
(SUBWAY_STATION_SEQ.NEXTVAL, '서울역', '1', 37.554264, 126.970626, '133', '1');
INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER) VALUES
(SUBWAY_STATION_SEQ.NEXTVAL, '홍대입구역', '2', 37.557192, 126.925381, '239', '1');
INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER) VALUES
(SUBWAY_STATION_SEQ.NEXTVAL, '잠실역', '2', 37.513292, 127.100109, '216', '1');
INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER) VALUES
(SUBWAY_STATION_SEQ.NEXTVAL, '사당역', '2', 37.476418, 126.981510, '234', '1');

-- 3. 따릉이 대여소 샘플 데이터
INSERT INTO BIKE_STATIONS (STATION_ID, STATION_NAME, LATITUDE, LONGITUDE, AVAILABLE_BIKES, TOTAL_DOCKS, DISTRICT, ADDRESS) VALUES
('ST-001', '강남역 1번출구', 37.498095, 127.027610, 12, 20, '강남구', '서울특별시 강남구 강남대로 지하396');
INSERT INTO BIKE_STATIONS (STATION_ID, STATION_NAME, LATITUDE, LONGITUDE, AVAILABLE_BIKES, TOTAL_DOCKS, DISTRICT, ADDRESS) VALUES
('ST-002', '서울역 광장', 37.554264, 126.970626, 8, 15, '중구', '서울특별시 중구 한강대로 405');
INSERT INTO BIKE_STATIONS (STATION_ID, STATION_NAME, LATITUDE, LONGITUDE, AVAILABLE_BIKES, TOTAL_DOCKS, DISTRICT, ADDRESS) VALUES
('ST-003', '홍대입구역', 37.557192, 126.925381, 15, 25, '마포구', '서울특별시 마포구 양화로 지하160');
INSERT INTO BIKE_STATIONS (STATION_ID, STATION_NAME, LATITUDE, LONGITUDE, AVAILABLE_BIKES, TOTAL_DOCKS, DISTRICT, ADDRESS) VALUES
('ST-004', '잠실역 2번출구', 37.513292, 127.100109, 20, 30, '송파구', '서울특별시 송파구 올림픽로 지하240');

-- 4. 공영 주차장 샘플 데이터
INSERT INTO PUBLIC_PARKING (PARKING_ID, PARKING_CODE, PARKING_NAME, ADDRESS, LATITUDE, LONGITUDE, TOTAL_SPACES, AVAILABLE_SPACES, PARKING_TYPE, OPERATION_TYPE, WEEKDAY_BEGIN_TIME, WEEKDAY_END_TIME, RATES, PAY_METHOD, TELEPHONE, REGION, DISTRICT) VALUES
(PARKING_SEQ.NEXTVAL, 'SEL-001', '강남역 공영주차장', '서울 강남구 강남대로 396', 37.498095, 127.027610, 200, 45, '노외', '공영', '00:00', '24:00', '기본 30분 1,000원, 추가 10분당 500원', '현금, 카드, 모바일', '02-1234-5678', '서울', '강남구');
INSERT INTO PUBLIC_PARKING (PARKING_ID, PARKING_CODE, PARKING_NAME, ADDRESS, LATITUDE, LONGITUDE, TOTAL_SPACES, AVAILABLE_SPACES, PARKING_TYPE, OPERATION_TYPE, WEEKDAY_BEGIN_TIME, WEEKDAY_END_TIME, RATES, PAY_METHOD, TELEPHONE, REGION, DISTRICT) VALUES
(PARKING_SEQ.NEXTVAL, 'SEL-002', '서울역 공영주차장', '서울 용산구 한강대로 405', 37.554264, 126.970626, 400, 156, '노외', '공영', '00:00', '24:00', '기본 30분 1,000원, 추가 10분당 500원', '현금, 카드, 모바일', '02-2345-6789', '서울', '용산구');
INSERT INTO PUBLIC_PARKING (PARKING_ID, PARKING_CODE, PARKING_NAME, ADDRESS, LATITUDE, LONGITUDE, TOTAL_SPACES, AVAILABLE_SPACES, PARKING_TYPE, OPERATION_TYPE, WEEKDAY_BEGIN_TIME, WEEKDAY_END_TIME, RATES, PAY_METHOD, TELEPHONE, REGION, DISTRICT) VALUES
(PARKING_SEQ.NEXTVAL, 'GG-001', '수원역 공영주차장', '경기 수원시 팔달구 매산로 1', 37.266219, 127.001087, 350, 142, '노외', '공영', '00:00', '24:00', '기본 30분 1,000원, 추가 10분당 500원', '현금, 카드, 모바일', '031-1234-5678', '경기', '수원시 팔달구');

-- 5. 정책 샘플 데이터
INSERT INTO POLICY (POLICY_ID, POLICY_NAME, POLICY_TYPE, ENABLED, START_DATE, END_DATE, TARGET_AREA, INCENTIVE_POINT, DESCRIPTION, TARGET_GROUP) VALUES
(POLICY_SEQ.NEXTVAL, '비혼잡 시간대 인센티브', 'off-peak', '1', TO_DATE('2026-01-01', 'YYYY-MM-DD'), TO_DATE('2026-12-31', 'YYYY-MM-DD'), '서울,경기', 500, '오전 10시~오후 4시 이용 시 포인트 지급', '전체');
INSERT INTO POLICY (POLICY_ID, POLICY_NAME, POLICY_TYPE, ENABLED, START_DATE, END_DATE, TARGET_AREA, INCENTIVE_POINT, DESCRIPTION, TARGET_GROUP) VALUES
(POLICY_SEQ.NEXTVAL, '친환경 교통수단 이용', 'eco', '1', TO_DATE('2026-01-01', 'YYYY-MM-DD'), TO_DATE('2026-12-31', 'YYYY-MM-DD'), '서울,경기,인천', 1000, '따릉이, 전기버스 이용 시 포인트 지급', '전체');
INSERT INTO POLICY (POLICY_ID, POLICY_NAME, POLICY_TYPE, ENABLED, START_DATE, END_DATE, TARGET_AREA, INCENTIVE_POINT, DESCRIPTION, TARGET_GROUP) VALUES
(POLICY_SEQ.NEXTVAL, '정액 요금제 (월간패스)', 'flat', '1', TO_DATE('2026-01-01', 'YYYY-MM-DD'), TO_DATE('2026-12-31', 'YYYY-MM-DD'), '서울,경기', 0, '월 50회 이용 가능 (59,000원)', '직장인');

-- 6. 제휴 상점 샘플 데이터
INSERT INTO SHOP (SHOP_ID, SHOP_NAME, CATEGORY, ADDRESS, LATITUDE, LONGITUDE, PHONE, RATING, DISCOUNT_RATE, VISIT_COUNT, OPENING_TIME, CLOSING_TIME, STATUS, ACTIVE, DESCRIPTION) VALUES
(SHOP_SEQ.NEXTVAL, '스타벅스 강남역점', '카페', '서울 강남구 강남대로 지하396', 37.498095, 127.027610, '02-1111-2222', 4.5, 10, 523, '07:00', '23:00', 'open', '1', '강남역 1번출구 앞 스타벅스');
INSERT INTO SHOP (SHOP_ID, SHOP_NAME, CATEGORY, ADDRESS, LATITUDE, LONGITUDE, PHONE, RATING, DISCOUNT_RATE, VISIT_COUNT, OPENING_TIME, CLOSING_TIME, STATUS, ACTIVE, DESCRIPTION) VALUES
(SHOP_SEQ.NEXTVAL, 'GS25 서울역점', '편의점', '서울 중구 한강대로 405', 37.554264, 126.970626, '02-2222-3333', 4.2, 5, 342, '00:00', '24:00', 'open', '1', '서울역 내부 편의점');
INSERT INTO SHOP (SHOP_ID, SHOP_NAME, CATEGORY, ADDRESS, LATITUDE, LONGITUDE, PHONE, RATING, DISCOUNT_RATE, VISIT_COUNT, OPENING_TIME, CLOSING_TIME, STATUS, ACTIVE, DESCRIPTION) VALUES
(SHOP_SEQ.NEXTVAL, '본죽 홍대점', '음식점', '서울 마포구 양화로 160', 37.557192, 126.925381, '02-3333-4444', 4.7, 15, 289, '10:00', '22:00', 'open', '1', '홍대입구역 근처 본죽');

-- 7. 이용 기록 샘플 데이터
INSERT INTO USAGE_RECORDS (RECORD_ID, USER_ID, TRANSPORT_TYPE, ROUTE_INFO, REGION, POINTS, POLICY_APPLIED, DAY_OF_WEEK) VALUES
(USAGE_SEQ.NEXTVAL, '1', 'SUBWAY', '강남역 → 서울역 (2호선)', '서울', 100, '1', 'MON');
INSERT INTO USAGE_RECORDS (RECORD_ID, USER_ID, TRANSPORT_TYPE, ROUTE_INFO, REGION, POINTS, POLICY_APPLIED, DAY_OF_WEEK) VALUES
(USAGE_SEQ.NEXTVAL, '2', 'BIKE', '강남역 1번출구 대여소', '서울', 50, '1', 'TUE');
INSERT INTO USAGE_RECORDS (RECORD_ID, USER_ID, TRANSPORT_TYPE, ROUTE_INFO, REGION, POINTS, POLICY_APPLIED, DAY_OF_WEEK) VALUES
(USAGE_SEQ.NEXTVAL, '3', 'PARKING', '서울역 공영주차장 (2시간)', '서울', 200, '0', 'WED');

-- 8. 포인트 거래 샘플 데이터
INSERT INTO POINT_TRANSACTIONS (TRANSACTION_ID, USER_ID, AMOUNT, TYPE, REASON) VALUES
(POINT_SEQ.NEXTVAL, 1, 1000, 'EARN', '회원가입 보너스');
INSERT INTO POINT_TRANSACTIONS (TRANSACTION_ID, USER_ID, AMOUNT, TYPE, REASON) VALUES
(POINT_SEQ.NEXTVAL, 1, 100, 'EARN', '지하철 이용 포인트');
INSERT INTO POINT_TRANSACTIONS (TRANSACTION_ID, USER_ID, AMOUNT, TYPE, REASON) VALUES
(POINT_SEQ.NEXTVAL, 2, 50, 'USE', '제휴 상점 할인 사용');

COMMIT;

-- =====================================================
-- 테이블 생성 확인
-- =====================================================
SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME;

-- =====================================================
-- 데이터 건수 확인
-- =====================================================
SELECT 'USERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM USERS
UNION ALL
SELECT 'POINT_TRANSACTIONS', COUNT(*) FROM POINT_TRANSACTIONS
UNION ALL
SELECT 'USAGE_RECORDS', COUNT(*) FROM USAGE_RECORDS
UNION ALL
SELECT 'SUBWAY_STATION', COUNT(*) FROM SUBWAY_STATION
UNION ALL
SELECT 'BIKE_STATIONS', COUNT(*) FROM BIKE_STATIONS
UNION ALL
SELECT 'PUBLIC_PARKING', COUNT(*) FROM PUBLIC_PARKING
UNION ALL
SELECT 'POLICY', COUNT(*) FROM POLICY
UNION ALL
SELECT 'SHOP', COUNT(*) FROM SHOP;

-- =====================================================
-- 스크립트 실행 완료
-- =====================================================
-- 실행 방법:
-- SQL*Plus> @CREATE_ALL_TABLES.sql
-- 또는 SQL Developer에서 전체 스크립트 실행
-- =====================================================
