-- =====================================================
-- 수도권 전체 지하철 노선 데이터 추가
-- =====================================================
-- 생성일: 2026-01-12
-- 설명: 서울 1-9호선, 인천1-2호선, 수인분당선, 공항철도,
--       경의중앙선, 신분당선, 경춘선, 우이신설선, 서해선,
--       김포골드라인, GTX-A 등 수도권 전체 노선
-- =====================================================

-- 기존 데이터 삭제 (선택사항)
-- DELETE FROM SUBWAY_STATION;

-- =====================================================
-- 인천1호선 (계양~국제업무지구) - 29개역
-- =====================================================
INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '계양', '인천1호선', 37.537888, 126.544417, 'I110', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '귤현', '인천1호선', 37.542292, 126.549583, 'I111', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '박촌', '인천1호선', 37.547208, 126.555750, 'I112', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '임학', '인천1호선', 37.552083, 126.562167, 'I113', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '계산', '인천1호선', 37.557958, 126.568583, 'I114', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '경인교대입구', '인천1호선', 37.563000, 126.576333, 'I115', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '작전', '인천1호선', 37.564792, 126.587833, 'I116', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '갈산', '인천1호선', 37.564625, 126.596167, 'I117', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '부평구청', '인천1호선', 37.567458, 126.607583, 'I118', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '부평', '인천1호선', 37.481600, 126.722350, 'I119', '1', '1호선,7호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '부평시장', '인천1호선', 37.485542, 126.720917, 'I120', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '부평삼거리', '인천1호선', 37.488958, 126.719417, 'I121', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '동수', '인천1호선', 37.494208, 126.716667, 'I122', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '부평삼거리', '인천1호선', 37.499375, 126.713750, 'I123', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '간석오거리', '인천1호선', 37.465542, 126.695333, 'I124', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '인천시청', '인천1호선', 37.459292, 126.691833, 'I125', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '예술회관', '인천1호선', 37.453542, 126.688500, 'I126', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '인천터미널', '인천1호선', 37.443375, 126.683917, 'I127', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '문학경기장', '인천1호선', 37.436708, 126.679917, 'I128', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '선학', '인천1호선', 37.428708, 126.676250, 'I129', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '신연수', '인천1호선', 37.419042, 126.672750, 'I130', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '원인재', '인천1호선', 37.411458, 126.667917, 'I131', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '동춘', '인천1호선', 37.405792, 126.662667, 'I132', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '동막', '인천1호선', 37.398625, 126.657917, 'I133', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '캠퍼스타운', '인천1호선', 37.393542, 126.653167, 'I134', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '테크노파크', '인천1호선', 37.387208, 126.649000, 'I135', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '지식정보단지', '인천1호선', 37.381792, 126.644917, 'I136', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '인천대입구', '인천1호선', 37.375042, 126.640000, 'I137', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '센트럴파크', '인천1호선', 37.389500, 126.654583, 'I138', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '국제업무지구', '인천1호선', 37.395125, 126.659250, 'I139', '0', NULL);

-- =====================================================
-- 인천2호선 (검단오류~운연) - 27개역
-- =====================================================
INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '검단오류', '인천2호선', 37.582083, 126.587500, 'I201', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '왕길', '인천2호선', 37.577917, 126.595417, 'I202', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '검단사거리', '인천2호선', 37.573750, 126.603333, 'I203', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '마전', '인천2호선', 37.569583, 126.611250, 'I204', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '완정', '인천2호선', 37.565417, 126.619167, 'I205', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '독정', '인천2호선', 37.561250, 126.627083, 'I206', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '검암', '인천2호선', 37.557083, 126.635000, 'I207', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '검바위', '인천2호선', 37.552917, 126.642917, 'I208', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '아시아드경기장', '인천2호선', 37.548750, 126.650833, 'I209', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '서구청', '인천2호선', 37.544583, 126.658750, 'I210', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '가정', '인천2호선', 37.540417, 126.666667, 'I211', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '가정중앙시장', '인천2호선', 37.536250, 126.674583, 'I212', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '석남', '인천2호선', 37.532083, 126.682500, 'I213', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '서부여성회관', '인천2호선', 37.527917, 126.690417, 'I214', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '인천가좌', '인천2호선', 37.523750, 126.698333, 'I215', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '가재울', '인천2호선', 37.519583, 126.706250, 'I216', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '주안국가산단', '인천2호선', 37.515417, 126.714167, 'I217', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '주안', '인천2호선', 37.463500, 126.679917, 'I218', '1', '1호선,수인분당선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '시민공원', '인천2호선', 37.459333, 126.687833, 'I219', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '석바위시장', '인천2호선', 37.455167, 126.695750, 'I220', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '인천시청', '인천2호선', 37.451000, 126.703667, 'I221', '1', '인천1호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '석촌', '인천2호선', 37.446833, 126.711583, 'I222', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '모래내시장', '인천2호선', 37.442667, 126.719500, 'I223', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '만수', '인천2호선', 37.438500, 126.727417, 'I224', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '남동구청', '인천2호선', 37.434333, 126.735333, 'I225', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '인천대공원', '인천2호선', 37.430167, 126.743250, 'I226', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '운연', '인천2호선', 37.426000, 126.751167, 'I227', '0', NULL);

-- =====================================================
-- 수인분당선 주요역 (인천~수원~왕십리) - 주요역만
-- =====================================================
INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '인천', '수인분당선', 37.476389, 126.616500, 'K272', '1', '1호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '신포', '수인분당선', 37.469639, 126.627167, 'K271', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '숭의', '수인분당선', 37.465778, 126.637694, 'K270', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '인하대', '수인분당선', 37.448889, 126.653167, 'K269', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '송도', '수인분당선', 37.405500, 126.640972, 'K268', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '연수', '수인분당선', 37.410639, 126.678306, 'K267', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '원인재', '수인분당선', 37.429694, 126.693361, 'K266', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '남동인더스파크', '수인분당선', 37.446417, 126.699944, 'K265', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '호구포', '수인분당선', 37.455944, 126.717722, 'K264', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '인천논현', '수인분당선', 37.463806, 126.735111, 'K263', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '소래포구', '수인분당선', 37.472694, 126.753083, 'K262', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '월곶', '수인분당선', 37.485750, 126.758500, 'K261', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '달월', '수인분당선', 37.494139, 126.762417, 'K260', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '오이도', '수인분당선', 37.344694, 126.674972, 'K259', '1', '4호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '정왕', '수인분당선', 37.347278, 126.693389, 'K258', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '신길온천', '수인분당선', 37.357083, 126.712639, 'K257', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '안산', '수인분당선', 37.337139, 126.826944, 'K256', '1', '4호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '고잔', '수인분당선', 37.311472, 126.835528, 'K255', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '수원', '수인분당선', 37.266083, 127.001250, 'K245', '1', '1호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '매교', '수인분당선', 37.275139, 127.018333, 'K244', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '수원시청', '수인분당선', 37.284056, 127.032167, 'K243', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '매탄권선', '수인분당선', 37.282222, 127.044944, 'K242', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '망포', '수인분당선', 37.287389, 127.058306, 'K241', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '영통', '수인분당선', 37.284250, 127.073167, 'K240', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '청명', '수인분당선', 37.285306, 127.092639, 'K239', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '상갈', '수인분당선', 37.297361, 127.107722, 'K238', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '기흥', '수인분당선', 37.275889, 127.115639, 'K237', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '신갈', '수인분당선', 37.266167, 127.115028, 'K236', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '구성', '수인분당선', 37.266861, 127.097667, 'K235', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '보정', '수인분당선', 37.269500, 127.085917, 'K234', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '죽전', '수인분당선', 37.321917, 127.106833, 'K233', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '오리', '수인분당선', 37.339750, 127.107278, 'K232', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '미금', '수인분당선', 37.349722, 127.109111, 'K231', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '정자', '수인분당선', 37.360028, 127.115472, 'K230', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '수서', '수인분당선', 37.487528, 127.100167, 'K217', '1', '3호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '복정', '수인분당선', 37.471056, 127.125611, 'K216', '1', '8호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '가천대', '수인분당선', 37.453139, 127.129333, 'K215', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '태평', '수인분당선', 37.449444, 127.129361, 'K214', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '모란', '수인분당선', 37.434361, 127.129083, 'K213', '1', '8호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '야탑', '수인분당선', 37.411500, 127.128083, 'K212', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '이매', '수인분당선', 37.400556, 127.127750, 'K211', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '서현', '수인분당선', 37.385500, 127.123583, 'K210', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '선릉', '수인분당선', 37.504583, 127.049000, 'K209', '1', '2호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '한티', '수인분당선', 37.515389, 127.060944, 'K208', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '도곡', '수인분당선', 37.491889, 127.053806, 'K207', '1', '3호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '구룡', '수인분당선', 37.486639, 127.065639, 'K206', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '개포동', '수인분당선', 37.484500, 127.076306, 'K205', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '왕십리', '수인분당선', 37.561694, 127.037222, 'K210', '1', '2호선,5호선,경의중앙선');

-- =====================================================
-- 공항철도 (서울역~인천공항2터미널) - 13개역
-- =====================================================
INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '서울역', '공항철도', 37.554264, 126.970626, 'A01', '1', '1호선,4호선,경의중앙선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '공덕', '공항철도', 37.544583, 126.951500, 'A02', '1', '5호선,6호선,경의중앙선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '홍대입구', '공항철도', 37.557192, 126.925381, 'A03', '1', '2호선,경의중앙선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '디지털미디어시티', '공항철도', 37.576583, 126.900694, 'A04', '1', '6호선,경의중앙선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '김포공항', '공항철도', 37.562434, 126.801058, 'A05', '1', '5호선,9호선,김포골드라인');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '계양', '공항철도', 37.537888, 126.544417, 'A06', '1', '인천1호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '검암', '공항철도', 37.557083, 126.635000, 'A07', '1', '인천2호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '청라국제도시', '공항철도', 37.537889, 126.549583, 'A08', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '영종', '공항철도', 37.485833, 126.498556, 'A09', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '운서', '공항철도', 37.495389, 126.490389, 'A10', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '공항화물청사', '공항철도', 37.494167, 126.445389, 'A11', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '인천공항1터미널', '공항철도', 37.450917, 126.440778, 'A12', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '인천공항2터미널', '공항철도', 37.493917, 126.493056, 'A13', '0', NULL);

-- =====================================================
-- 경의중앙선 주요역 (문산~용문) - 주요역만
-- =====================================================
INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '문산', '경의중앙선', 37.862417, 126.783056, 'P313', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '파주', '경의중앙선', 37.760234, 126.723812, 'P312', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '운정', '경의중앙선', 37.732333, 126.790361, 'P311', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '금촌', '경의중앙선', 37.711056, 126.791917, 'P310', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '금릉', '경의중앙선', 37.677694, 126.796861, 'P309', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '운천', '경의중앙선', 37.656139, 126.819194, 'P308', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '일산', '경의중앙선', 37.696342, 126.770729, 'P313', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '탄현', '경의중앙선', 37.686028, 126.816333, 'P307', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '야당', '경의중앙선', 37.644861, 126.860528, 'P306', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '백마', '경의중앙선', 37.636139, 126.881917, 'P305', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '풍산', '경의중앙선', 37.616917, 126.897694, 'P304', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '대곡', '경의중앙선', 37.635333, 126.892833, 'P318', '1', '3호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '행신', '경의중앙선', 37.637833, 126.924472, 'P315', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '강매', '경의중앙선', 37.624083, 126.912917, 'P314', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '수색', '경의중앙선', 37.583583, 126.896750, 'P316', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '디지털미디어시티', '경의중앙선', 37.576583, 126.900694, 'P317', '1', '6호선,공항철도');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '가좌', '경의중앙선', 37.567583, 126.916806, 'P314', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '신촌', '경의중앙선', 37.554444, 126.936861, 'P313', '1', '2호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '서강대', '경의중앙선', 37.548750, 126.940028, 'P312', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '용산', '경의중앙선', 37.529778, 126.964444, 'P311', '1', '1호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '이촌', '경의중앙선', 37.522361, 126.975028, 'P310', '1', '4호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '양평', '경의중앙선', 37.532833, 126.990222, 'P140', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '신용산', '경의중앙선', 37.528250, 126.964917, 'P139', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '옥수', '경의중앙선', 37.540444, 127.018278, 'P138', '1', '3호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '응봉', '경의중앙선', 37.548917, 127.031611, 'P137', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '청량리', '경의중앙선', 37.580056, 127.046972, 'P124', '1', '1호선,경춘선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '회기', '경의중앙선', 37.589528, 127.056944, 'P123', '1', '1호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '중랑', '경의중앙선', 37.595833, 127.082750, 'P122', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '상봉', '경의중앙선', 37.596667, 127.085472, 'P121', '1', '7호선,경춘선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '망우', '경의중앙선', 37.599722, 127.091833, 'P120', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '양원', '경의중앙선', 37.605694, 127.111861, 'P119', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '구리', '경의중앙선', 37.593861, 127.139222, 'P118', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '도농', '경의중앙선', 37.603333, 127.159028, 'P117', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '양정', '경의중앙선', 37.609083, 127.177639, 'P116', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '덕소', '경의중앙선', 37.604306, 127.211306, 'P115', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '팔당', '경의중앙선', 37.595639, 127.253167, 'P114', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '운길산', '경의중앙선', 37.597139, 127.310306, 'P113', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '양수', '경의중앙선', 37.620139, 127.383111, 'P112', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '신원', '경의중앙선', 37.606194, 127.446528, 'P111', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '국수', '경의중앙선', 37.583750, 127.488583, 'P110', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '용문', '경의중앙선', 37.542111, 127.579861, 'P109', '0', NULL);

-- =====================================================
-- 신분당선 (강남~광교) - 12개역
-- =====================================================
INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '강남', '신분당선', 37.497952, 127.027926, 'D07', '1', '2호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '양재', '신분당선', 37.484034, 127.034099, 'D08', '1', '3호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '양재시민의숲', '신분당선', 37.470811, 127.038988, 'D09', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '청계산입구', '신분당선', 37.435583, 127.045667, 'D10', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '판교', '신분당선', 37.394739, 127.111181, 'D11', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '정자', '신분당선', 37.360028, 127.115472, 'D12', '1', '수인분당선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '미금', '신분당선', 37.349722, 127.109111, 'D13', '1', '수인분당선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '동천', '신분당선', 37.342028, 127.103167, 'D14', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '수지구청', '신분당선', 37.322889, 127.093111, 'D15', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '성복', '신분당선', 37.306833, 127.081917, 'D16', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '상현', '신분당선', 37.300722, 127.071361, 'D17', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '광교중앙', '신분당선', 37.298361, 127.063417, 'D18', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '광교', '신분당선', 37.301833, 127.045833, 'D19', '0', NULL);

-- =====================================================
-- 경춘선 (청량리~춘천) - 주요역만
-- =====================================================
INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '청량리', '경춘선', 37.580056, 127.046972, 'P117', '1', '1호선,경의중앙선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '회기', '경춘선', 37.589528, 127.056944, 'P116', '1', '1호선,경의중앙선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '중랑', '경춘선', 37.595833, 127.082750, 'P115', '1', '경의중앙선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '상봉', '경춘선', 37.596667, 127.085472, 'P114', '1', '7호선,경의중앙선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '망우', '경춘선', 37.599722, 127.091833, 'P113', '1', '경의중앙선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '신내', '경춘선', 37.610139, 127.097833, 'P112', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '갈매', '경춘선', 37.616806, 127.120722, 'P111', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '별내', '경춘선', 37.635611, 127.126278, 'P110', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '퇴계원', '경춘선', 37.649472, 127.143806, 'P109', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '사릉', '경춘선', 37.659083, 127.184917, 'P108', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '금곡', '경춘선', 37.663028, 127.215667, 'P107', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '평내호평', '경춘선', 37.665694, 127.247639, 'P106', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '천마산', '경춘선', 37.684306, 127.280972, 'P105', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '마석', '경춘선', 37.700917, 127.306167, 'P104', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '대성리', '경춘선', 37.715083, 127.397833, 'P103', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '청평', '경춘선', 37.740528, 127.439750, 'P102', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '가평', '경춘선', 37.769333, 127.511750, 'P101', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '굴봉산', '경춘선', 37.806722, 127.560833, 'P100', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '백양리', '경춘선', 37.846528, 127.602528, 'P99', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '강촌', '경춘선', 37.873278, 127.637111, 'P98', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '김유정', '경춘선', 37.888806, 127.668194, 'P97', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '남춘천', '경춘선', 37.862083, 127.729000, 'P96', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '춘천', '경춘선', 37.885278, 127.720056, 'P95', '0', NULL);

-- =====================================================
-- 우이신설선 (우이~신설동) - 13개역
-- =====================================================
INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '북한산우이', '우이신설선', 37.663083, 127.012417, 'U113', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '솔샘', '우이신설선', 37.659917, 127.014833, 'U112', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '4·19민주묘지', '우이신설선', 37.656750, 127.017250, 'U111', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '가오리', '우이신설선', 37.653583, 127.019667, 'U110', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '화계', '우이신설선', 37.650417, 127.022083, 'U109', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '삼양', '우이신설선', 37.647250, 127.024500, 'U108', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '삼양사거리', '우이신설선', 37.644083, 127.026917, 'U107', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '솔밭공원', '우이신설선', 37.640917, 127.029333, 'U106', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '북한산보국문', '우이신설선', 37.637750, 127.031750, 'U105', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '정릉', '우이신설선', 37.604028, 127.015306, 'U104', '1', '6호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '성신여대입구', '우이신설선', 37.592750, 127.017167, 'U103', '1', '4호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '보문', '우이신설선', 37.588750, 127.019583, 'U102', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '신설동', '우이신설선', 37.575111, 127.025083, 'U101', '1', '1호선,2호선');

-- =====================================================
-- 서해선 (소사~원시) - 10개역
-- =====================================================
INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '소사', '서해선', 37.478944, 126.790306, 'S01', '1', '1호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '소새울', '서해선', 37.470806, 126.803139, 'S02', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '시흥대야', '서해선', 37.438222, 126.828694, 'S03', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '신천', '서해선', 37.407056, 126.847750, 'S04', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '신현', '서해선', 37.382472, 126.864389, 'S05', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '시흥시청', '서해선', 37.365639, 126.883222, 'S06', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '시흥능곡', '서해선', 37.347194, 126.901944, 'S07', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '달미', '서해선', 37.328750, 126.920556, 'S08', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '선부', '서해선', 37.310306, 126.939167, 'S09', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '원시', '서해선', 37.291861, 126.957778, 'S10', '0', NULL);

-- =====================================================
-- 김포골드라인 (김포공항~양촌) - 10개역
-- =====================================================
INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '김포공항', '김포골드라인', 37.562434, 126.801058, 'G01', '1', '5호선,9호선,공항철도');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '고촌', '김포골드라인', 37.587639, 126.769333, 'G02', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '풍무', '김포골드라인', 37.606778, 126.727833, 'G03', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '사우', '김포골드라인', 37.619083, 126.698500, 'G04', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '걸포북변', '김포골드라인', 37.631389, 126.669167, 'G05', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '마산', '김포골드라인', 37.643694, 126.639833, 'G06', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '장기', '김포골드라인', 37.649234, 126.713812, 'G07', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '운양', '김포골드라인', 37.656750, 126.584500, 'G08', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '걸포', '김포골드라인', 37.662250, 126.555167, 'G09', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '양촌', '김포골드라인', 37.657833, 126.525833, 'G10', '0', NULL);

-- =====================================================
-- 서울 1호선 주요역 추가 (신도림 포함)
-- =====================================================
INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '서울역', '1호선', 37.554264, 126.970626, '133', '1', '4호선,경의중앙선,공항철도');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '시청', '1호선', 37.565092, 126.976914, '132', '1', '2호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '종각', '1호선', 37.570256, 126.982945, '131', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '종로3가', '1호선', 37.571607, 126.991806, '130', '1', '3호선,5호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '종로5가', '1호선', 37.572917, 127.000389, '129', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '동대문', '1호선', 37.571389, 127.009722, '128', '1', '4호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '동묘앞', '1호선', 37.571250, 127.016278, '127', '1', '6호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '신설동', '1호선', 37.575111, 127.025083, '126', '1', '2호선,우이신설선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '제기동', '1호선', 37.579639, 127.035583, '125', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '청량리', '1호선', 37.580056, 127.046972, '124', '1', '경의중앙선,경춘선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '회기', '1호선', 37.589528, 127.056944, '123', '1', '경의중앙선,경춘선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '외대앞', '1호선', 37.596667, 127.064361, '122', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '신이문', '1호선', 37.608806, 127.072139, '121', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '석계', '1호선', 37.613806, 127.077750, '120', '1', '6호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '광운대', '1호선', 37.622083, 127.061917, '119', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '월계', '1호선', 37.618083, 127.057917, '118', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '녹천', '1호선', 37.624972, 127.044333, '117', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '창동', '1호선', 37.653611, 127.047222, '116', '1', '4호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '방학', '1호선', 37.668472, 127.045306, '115', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '도봉', '1호선', 37.680194, 127.043639, '114', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '도봉산', '1호선', 37.689833, 127.045944, '113', '1', '7호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '망월사', '1호선', 37.699167, 127.048333, '112', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '회룡', '1호선', 37.709500, 127.050722, '111', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '의정부', '1호선', 37.738234, 127.046723, '110', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '부평', '1호선', 37.481600, 126.722350, '147', '1', '인천1호선,7호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '주안', '1호선', 37.463500, 126.679917, '148', '1', '인천2호선,수인분당선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '도화', '1호선', 37.468056, 126.638111, '149', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '제물포', '1호선', 37.473083, 126.630250, '150', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '인천', '1호선', 37.476389, 126.616500, '151', '1', '수인분당선');

-- =====================================================
-- 신도림역 추가 (1호선, 2호선 환승)
-- =====================================================
INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '신도림', '1호선', 37.508639, 126.891167, '140', '1', '2호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '신도림', '2호선', 37.508639, 126.891167, '234', '1', '1호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '대림', '2호선', 37.493667, 126.895583, '233', '1', '7호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '구로디지털단지', '2호선', 37.485302, 126.901489, '232', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '대방', '1호선', 37.513417, 126.926194, '139', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '노량진', '1호선', 37.514056, 126.942417, '138', '1', '9호선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '용산', '1호선', 37.529778, 126.964444, '137', '1', '경의중앙선');

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '송내', '1호선', 37.493361, 126.752833, '146', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '부천', '1호선', 37.485833, 126.766167, '145', '0', NULL);

INSERT INTO SUBWAY_STATION (ID, STATION_NAME, LINE_NUMBER, LATITUDE, LONGITUDE, STATION_CODE, IS_TRANSFER, TRANSFER_LINES)
VALUES (SUBWAY_STATION_SEQ.NEXTVAL, '소사', '1호선', 37.478944, 126.790306, '144', '1', '서해선');

COMMIT;

-- =====================================================
-- 데이터 건수 확인
-- =====================================================
SELECT LINE_NUMBER, COUNT(*) AS STATION_COUNT
FROM SUBWAY_STATION
GROUP BY LINE_NUMBER
ORDER BY LINE_NUMBER;

SELECT '전체 역 수: ' || COUNT(*) AS TOTAL_STATIONS FROM SUBWAY_STATION;

-- =====================================================
-- 환승역 확인
-- =====================================================
SELECT STATION_NAME, LINE_NUMBER, TRANSFER_LINES
FROM SUBWAY_STATION
WHERE IS_TRANSFER = '1'
ORDER BY STATION_NAME;

-- =====================================================
-- 스크립트 실행 완료
-- =====================================================
